# Generated by Django 2.2 on 2020-01-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=200)),
                ('product_price', models.FloatField()),
                ('product_total', models.FloatField()),
                ('product_detail', models.CharField(max_length=200)),
                ('product_company', models.CharField(max_length=200)),
                ('product_discount', models.FloatField(null=True)),
                ('product_image', models.FileField(blank=True, null=True, upload_to='document/product')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('itemCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshopadmin.itemCategory')),
            ],
        ),
    ]
