# Generated by Django 2.2 on 2020-01-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopadmin', '0004_auto_20200121_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='itemCategory',
            new_name='itemCategoryid',
        ),
    ]
