# Generated by Django 2.2 on 2020-01-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopadmin', '0005_auto_20200121_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='itemCategoryid',
            new_name='itemCategory_id',
        ),
    ]
