# Generated by Django 2.2 on 2020-01-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopadmin', '0006_auto_20200121_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to='document/company'),
        ),
    ]
