# Generated by Django 2.2 on 2020-01-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopadmin', '0007_auto_20200121_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='itemCategory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshopadmin.itemCategory'),
        ),
    ]
