# Generated by Django 2.2 on 2020-01-21 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopadmin', '0008_auto_20200121_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='itemCategory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshopadmin.itemCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_detail',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_discount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_total',
            field=models.CharField(max_length=200),
        ),
    ]
