# Generated by Django 2.2 on 2020-01-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopadmin', '0011_auto_20200131_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(null=True, upload_to='document/company'),
        ),
    ]
