# Generated by Django 2.2 on 2020-01-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopadmin', '0012_auto_20200131_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(upload_to='document/company'),
        ),
    ]
