# Generated by Django 2.2 on 2020-01-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregistration',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='document/company'),
        ),
    ]
