# Generated by Django 2.2 on 2020-01-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200105_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregistration',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
